name: Import new repositories into snyk

env: 
 GITHUB_TOKEN: ${{ secrets.SNYK_IMPORT_GITHUB_TOKEN }}
 SNYK_TOKEN: ${{ secrets.SNYK_IMPORT_SNYK_TOKEN}}
 SNYK_LOG_PATH: "."
 SNYK_IMPORT_PATH: "."
 SNYK_ORG_ID: 50400029-a7f7-4be2-8d94-cc1ef051efa6
on:
  push:
  # schedule:
  # # run on every weekday (mon - fri) on 3:30 UST
  #   - cron: '30 3 * * 1-5'
jobs:
  Snyk-import:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install snyk-api-import
        run: npm install snyk-api-import@latest --location=global
      - name: List all github repo data in github-import-targets.json
        run: DEBUG=snyk* snyk-api-import import:data --orgsData=./snyk-created-orgs.json --integrationType=github-enterprise
      - name: Creates log files containing details on existing repositories
        run: DEBUG=snyk* snyk-api-import list:imported --integrationType=github-enterprise --orgId=${{ env.SNYK_ORG_ID}}
        # Rename github-import-targets.json to import-projects.json
      - name: Rename file
        run: mv github-import-targets.json import-projects.json
      - name: Import the repositories
        run: DEBUG=snyk* snyk-api-import import
      - name: running summary generator
        run: node snyk-import-repo-summary-generator.js
