name: Import new repositories into snyk

env: 
 GITHUB_TOKEN: ${{ secrets.SNYK_IMPORT_GITHUB_TOKEN }}
 SNYK_TOKEN: ${{ secrets.SNYK_IMPORT_SNYK_TOKEN}}
 SNYK_LOG_PATH: "."
 SNYK_IMPORT_PATH: "."
 SNYK_ORG_ID: 50400029-a7f7-4be2-8d94-cc1ef051efa6
on:
  push:
#   schedule:
  
  # run on every weekday (mon - fri) on 3:30 UST
#     - cron: '30 3 * * 1-5'
jobs:
  Snyk-import:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Download snyk-api-import-linux
        run: wget -c https://github.com/snyk-tech-services/snyk-api-import/releases/download/v1.90.0/snyk-api-import-linux
      - name: Download snyk-api-import-linux hash
        run: wget -c https://github.com/snyk-tech-services/snyk-api-import/releases/download/v1.90.0/snyk-api-import-linux.sha256
      - name: Check hash values
        run: |
             sha256sum snyk-api-import-linux > hashed-snyk-api-import-linux.sha256
             cmp snyk-api-import-linux.sha256 hashed-snyk-api-import-linux.sha256 || exit 1
      - name: exceute access to snyk-api-import-linux
        run: chmod 711 snyk-api-import-linux
      - name: Install snyk-api-import
        run: npm install snyk-api-import@latest -g
      - name: List all github repo data in github-enterprise-import-targets.json
        run: DEBUG=snyk* snyk-api-import import:data --orgsData=./snyk-created-orgs.json --source=github-enterprise --integrationType=github-enterprise
      - name: Creates log files containing details on existing repositories
        run: DEBUG=snyk* ./snyk-api-import-linux list:imported --integrationType=github-enterprise --orgId=${{ env.SNYK_ORG_ID}}
        # Rename github-enterprise-import-targets.json to import-projects.json
      - name: Rename file
        run: mv github-enterprise-import-targets.json import-projects.json
      - name: Import the repositories
        run: DEBUG=snyk* snyk-api-import import > synk-api-import-output.txt
        
      - name: running summary generator
        run: node snyk-import-repo-summary-generator.mjs
